'use client';

import { useState, useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Button, Spinner } from '@trading-game/design-intelligence-layer';
import { useBalanceStore } from '@/stores/balance-store';
import { useIsLandscape } from '@/hooks/use-landscape';
import { useIndexAscent } from '@/hooks/use-index-ascent';
import {
  CRASH_HOUSE_EDGE,
  getMilestoneTable,
  MIN_CASHOUT_MULTIPLIER,
} from '@/lib/games/index-ascent';
import { CRASH_SYMBOLS } from '@/types';
import type { CrashSymbol } from '@/types';
import { GameShell } from '@/components/games/shared/game-shell';
import { GameViewport, GameNotice } from '@/components/games/shared/game-layout';
import { StakeDock } from '@/components/games/shared/stake-dock';
import { ResultOverlay } from '@/components/games/shared/result-overlay';
import { LiveTickChart } from '@/components/games/shared/live-tick-chart';
import { ConnectionIndicator } from '@/components/layout/connection-indicator';
import { AscentCurve } from './ascent-curve';
import type { GameInfoSection } from '@/components/games/shared/game-info-drawer';

const AUTO_CASHOUT_PRESETS = [1.5, 2, 5, 10] as const;

export function IndexAscentGame() {
  const { balance } = useBalanceStore();
  const isLandscape = useIsLandscape();

  const [symbol, setSymbol] = useState<CrashSymbol>('CRASH150N');
  const [stake, setStake] = useState(100);
  const [autoCashout, setAutoCashout] = useState<number | null>(null);

  const {
    phase,
    multiplier,
    ticksSurvived,
    curve,
    ticks,
    marketStreak,
    marketCrashes,
    lastResult,
    roundHistory,
    launch,
    cashOut,
    reset,
  } = useIndexAscent(symbol);

  const flying = phase === 'flying';
  const potentialWin = stake * multiplier;
  const maxStake = Math.max(10, Math.min(balance, 5000));
  const milestones = getMilestoneTable(
    CRASH_SYMBOLS.find((s) => s.id === symbol)!.avgTicksPerCrash
  ).filter((m) => Number.isFinite(m.ticks));

  const showResultOverlay =
    lastResult !== null && (phase === 'cashed_out' || phase === 'crashed');

  const handleEnter = useCallback(() => {
    launch(stake, autoCashout);
  }, [launch, stake, autoCashout]);

  const infoSections: GameInfoSection[] = [
    {
      id: 'milestones',
      label: 'Targets',
      content: (
        <div className="space-y-2">
          <div className="grid grid-cols-3 gap-2 text-xs font-medium uppercase tracking-wide text-on-subtle">
            <span>Exit at</span>
            <span>Time</span>
            <span className="text-right">Survival</span>
          </div>
          {milestones.map((m) => (
            <div
              key={m.multiplier}
              className="grid grid-cols-3 gap-2 rounded-lg bg-subtle px-3 py-2 text-xs text-on-subtle"
            >
              <span className="font-display tabular-nums text-on-prominent">
                {m.multiplier}x
              </span>
              <span className="font-display tabular-nums">
                {m.seconds >= 120 ? `${Math.round(m.seconds / 60)} min` : `${m.seconds}s`}
              </span>
              <span className="text-right font-display tabular-nums">
                {(m.survivalProb * 100).toFixed(1)}%
              </span>
            </div>
          ))}
          <p className="text-xs text-on-subtle">
            Payouts carry a {(CRASH_HOUSE_EDGE * 100).toFixed(0)}% platform margin at
            every exit point.
          </p>
        </div>
      ),
    },
    {
      id: 'history',
      label: 'History',
      content: roundHistory.length ? (
        <div className="space-y-2">
          {roundHistory.map((r) => (
            <div
              key={r.id}
              className="flex items-center justify-between rounded-lg bg-subtle px-3 py-2 text-xs text-on-subtle"
            >
              <span>Round {r.id}</span>
              <span className="font-display tabular-nums text-on-prominent">
                {r.multiplier.toFixed(2)}x
              </span>
              <span
                className={
                  r.outcome === 'cashed_out' ? 'text-semantic-win' : 'text-semantic-loss'
                }
              >
                {r.outcome === 'cashed_out'
                  ? `+${Math.round(r.winAmount).toLocaleString()}`
                  : `−${Math.round(r.stake).toLocaleString()}`}
              </span>
            </div>
          ))}
        </div>
      ) : (
        <p className="text-sm text-on-subtle">No rounds yet.</p>
      ),
    },
    {
      id: 'rules',
      label: 'Rules',
      content: (
        <div className="space-y-2 text-sm text-on-subtle">
          <p>
            Your return multiplier builds on every tick the Deriv Crash index
            ascends without correcting. Corrections are generated by
            Deriv&apos;s market engine — not by this game.
          </p>
          <p>
            A Crash N index corrects once every N ticks on average, and the odds
            are memoryless: every tick carries the same 1-in-N correction risk
            regardless of how long the ascent has run.
          </p>
          <p>
            Exit any time to lock in the current multiplier. If the index
            corrects first, the position is closed at a loss.
          </p>
        </div>
      ),
    },
  ];

  return (
    <GameShell infoSections={infoSections} showSymbolPicker={false}>
      <GameViewport
        market={
          ticks.length > 0 ? (
            <div className="shrink-0 px-4 pt-2 pb-1 border-b border-border-subtle">
              <div className="relative overflow-hidden rounded-lg">
                <LiveTickChart ticks={ticks} className="w-full" />
                <div className="pointer-events-none absolute inset-x-0 top-0 flex items-start justify-between px-2 pt-1.5">
                  <div className="pointer-events-auto rounded bg-card/90 px-2 py-0.5 backdrop-blur-sm border border-border-subtle">
                    <ConnectionIndicator />
                  </div>
                  <div className="rounded bg-card/90 px-2 py-0.5 backdrop-blur-sm border border-border-subtle">
                    <span className="text-[10px] text-on-subtle">
                      Run <span className="font-display tabular-nums text-on-prominent">{marketStreak}</span> ticks
                    </span>
                  </div>
                </div>
              </div>
            </div>
          ) : (
            <div className="shrink-0 flex items-center justify-center py-6 border-b border-border-subtle">
              <Spinner />
            </div>
          )
        }
        play={
          <div className="flex flex-col flex-1 min-h-0 px-4 py-3">
            {marketCrashes.length > 0 ? (
              <div className="shrink-0 mb-2 flex items-center gap-1.5 overflow-x-auto">
                <span className="text-[10px] uppercase tracking-wide text-on-subtle shrink-0">
                  Recent corrections
                </span>
                {marketCrashes.map((m, i) => (
                  <span
                    key={`${i}-${m}`}
                    className={`shrink-0 rounded px-1.5 py-0.5 text-[10px] font-display tabular-nums ${
                      m >= 2
                        ? 'bg-semantic-win/10 text-semantic-win'
                        : 'bg-semantic-loss/10 text-semantic-loss'
                    }`}
                  >
                    {m.toFixed(2)}x
                  </span>
                ))}
              </div>
            ) : null}

            <div className="relative flex-1 min-h-[220px] rounded-xl border border-border-subtle bg-prominent overflow-hidden">
              <AscentCurve curve={curve} phase={phase} className="absolute inset-0" />

              <div className="absolute left-3 top-3 rounded-lg border border-border-subtle bg-card/90 px-3 py-2 shadow-sm backdrop-blur-sm">
                <p className="body-xs text-on-subtle uppercase">Return</p>
                <motion.p
                  key={`${phase}-${multiplier.toFixed(2)}`}
                  initial={{ scale: 1.04, opacity: 0.6 }}
                  animate={{ scale: 1, opacity: 1 }}
                  className={`font-display font-bold tabular-nums ${
                    isLandscape ? 'text-3xl' : 'text-4xl'
                  } ${
                    phase === 'crashed'
                      ? 'text-semantic-loss'
                      : phase === 'cashed_out'
                        ? 'text-semantic-win'
                        : 'text-on-prominent'
                  }`}
                >
                  {multiplier.toFixed(2)}x
                </motion.p>
              </div>

              <div className="absolute right-3 top-3 rounded-full border border-border-subtle bg-card/90 px-2.5 py-1 text-[10px] text-on-subtle shadow-sm backdrop-blur-sm tabular-nums">
                {flying
                  ? `${ticksSurvived} tick${ticksSurvived === 1 ? '' : 's'}${autoCashout ? ` · auto ${autoCashout}x` : ''}`
                  : phase === 'idle'
                    ? 'Waiting to enter'
                    : phase === 'cashed_out'
                      ? 'Position closed'
                      : 'Index corrected'}
              </div>

              {phase === 'idle' ? (
                <div className="absolute inset-x-4 bottom-5 text-center">
                  <p className="text-sm font-medium text-on-prominent">Your return builds one tick at a time</p>
                  <p className="mt-1 text-xs text-on-subtle">Enter now, then exit before the next correction.</p>
                </div>
              ) : null}

              <AnimatePresence>
                {phase === 'crashed' ? (
                  <motion.div
                    className="absolute inset-0 bg-semantic-loss/15"
                    initial={{ opacity: 0 }}
                    animate={{ opacity: [0, 1, 0.4] }}
                    exit={{ opacity: 0 }}
                    transition={{ duration: 0.6 }}
                  />
                ) : null}
              </AnimatePresence>
            </div>

            <div className="shrink-0 mt-2 space-y-1.5 rounded-lg border border-border-subtle bg-subtle p-1.5">
              <div className="flex items-center gap-1">
                <span className="w-16 shrink-0 pl-1 text-[10px] uppercase tracking-wide text-on-subtle">Index</span>
                {CRASH_SYMBOLS.map((s) => (
                  <button
                    key={s.id}
                    type="button"
                    disabled={flying}
                    onClick={() => setSymbol(s.id)}
                    className={`min-h-[32px] flex-1 rounded-md border px-2 text-xs font-medium transition-colors disabled:opacity-50 ${
                      symbol === s.id
                        ? 'border-border-prominent bg-prominent text-on-prominent shadow-sm'
                        : 'border-transparent text-on-subtle'
                    }`}
                  >
                    {s.name.replace('Crash ', '')}
                  </button>
                ))}
              </div>
              <div className="flex items-center gap-1">
                <span className="w-16 shrink-0 pl-1 text-[10px] uppercase tracking-wide text-on-subtle">Auto exit</span>
                <button
                  type="button"
                  disabled={flying}
                  onClick={() => setAutoCashout(null)}
                  className={`min-h-[32px] flex-1 rounded-md text-xs font-display tabular-nums transition-colors disabled:opacity-50 ${
                    autoCashout === null ? 'bg-prominent text-on-prominent shadow-sm' : 'text-on-subtle'
                  }`}
                >
                  Off
                </button>
                {AUTO_CASHOUT_PRESETS.map((preset) => (
                  <button
                    key={preset}
                    type="button"
                    disabled={flying}
                    onClick={() => setAutoCashout(preset)}
                    className={`min-h-[32px] flex-1 rounded-md text-xs font-display tabular-nums transition-colors disabled:opacity-50 ${
                      autoCashout === preset ? 'bg-prominent text-on-prominent shadow-sm' : 'text-on-subtle'
                    }`}
                  >
                    {preset}x
                  </button>
                ))}
              </div>
            </div>
          </div>
        }
        dock={
          <StakeDock
            stake={stake}
            max={maxStake}
            balance={balance}
            onStakeChange={setStake}
            stakeDisabled={flying}
            showSlider={!flying}
            footer={
              flying ? (
                <>
                  Exit now:{' '}
                  <span className="font-display font-semibold text-semantic-win tabular-nums">
                    {potentialWin.toFixed(0)}
                  </span>{' '}
                  credits
                </>
              ) : undefined
            }
            actions={
              flying ? (
                <Button
                  variant="primary"
                  className="w-full min-h-[52px] text-base"
                  disabled={multiplier < MIN_CASHOUT_MULTIPLIER && ticksSurvived < 1}
                  onClick={cashOut}
                >
                  Exit {multiplier.toFixed(2)}x
                </Button>
              ) : (
                <Button
                  variant="primary"
                  className="w-full min-h-[52px] text-base"
                  disabled={stake > balance || balance <= 0 || ticks.length === 0}
                  onClick={handleEnter}
                >
                  Enter position
                </Button>
              )
            }
          />
        }
      />

      <ResultOverlay
        open={showResultOverlay}
        won={lastResult?.outcome === 'cashed_out'}
        title={lastResult?.outcome === 'cashed_out' ? 'Position closed' : 'Index corrected'}
        subtitle={
          lastResult?.outcome === 'cashed_out'
            ? `Exited at ${lastResult.multiplier.toFixed(2)}x.`
            : `The index corrected at ${lastResult?.multiplier.toFixed(2)}x.`
        }
        amount={
          lastResult?.outcome === 'cashed_out' ? lastResult.winAmount : lastResult?.stake
        }
        amountLabel="credits"
        onDismiss={reset}
        primaryAction={{ label: 'Trade again', onClick: reset }}
      />
    </GameShell>
  );
}
